Models/Chef.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ChefsNDishes.Validators;

namespace ChefsNDishes.Models
{
    public class Chef
    {
        [Key]
        public int ChefId { get; set; }

        [Required]
        [Display(Name="First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name="Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name="Date of Birth")]
        [Birthday]
        public DateTime Birthday { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [Required]
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        public List<Dish> SignatureDishes { get; set; }
    }
}

Models/Dish.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ChefsNDishes.Models
{
    public class Dish
    {
        [Key]
        public int DishId { get; set; }

        [Required]
        [Display(Name="Dish Name")]
        public string DishName { get; set; }

        [Required]
        [Range(0, int.MaxValue)]
        public int Calories { get; set; }

        [Required]
        [Range(1, 5)]
        public int Tastiness { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [Required]
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        [Required]
        [Display(Name="Chef")]
        public int ChefId { get; set; }

        public Chef Creator { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ChefsNDishes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MyContext.cs
using Microsoft.EntityFrameworkCore;

namespace ChefsNDishes.Models
{
    public class MyContext : DbContext
    {
        // base() calls the parent class' constructor passing the "options" parameter along
        public MyContext(DbContextOptions options) : base(options) { }

        public DbSet<Chef> Chefs { get; set; }

        public DbSet<Dish> Dishes { get; set; }
    }
}

Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChefsNDishes.Models;

namespace ChefsNDishes.Controllers
{
    public class ChefController : Controller
    {
        private MyContext dbContext;

        public ChefController(MyContext context)
        {
            dbContext = context;
        }


        [HttpGet]
        [Route("chefs")]
        public IActionResult ShowChefs()
        {
            var chefs = dbContext.Chefs.ToList();

            return View(chefs);
        }

        [HttpGet]
        [Route("chefs/new")]
        public IActionResult NewChef()
        {
            return View("NewChefForm");
        }

        [HttpPost]
        [Route("chefs/new")]
        public IActionResult CreateNewChef(Chef newChef)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(newChef);
                dbContext.SaveChanges();

                return RedirectToAction("ShowChefs");
            }
            else
            {
                return View("NewChefForm");
            }
        }
    }
}

Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ChefsNDishes.Models;

namespace ChefsNDishes.Controllers
{
    public class DishController : Controller
    {
        private MyContext dbContext;

        public DishController(MyContext context)
        {
            dbContext = context;
        }

        [HttpGet]
        [Route("dishes")]
        public IActionResult ShowDishes()
        {
            var dishes = dbContext.Dishes.Include(x => x.Creator).ToList();
            return View(dishes);
        }

        [HttpGet]
        [Route("dishes/new")]
        public IActionResult NewDish()
        {
            var chefs = dbContext.Chefs.OrderBy(c => c.FirstName).ToList();
            ViewBag.Chefs = chefs;

            return View("NewDishForm");
        }

        [HttpPost]
        [Route("dishes/new")]
        public IActionResult CreateNewDish(Dish newDish)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(newDish);
                dbContext.SaveChanges();

                return RedirectToAction("ShowDishes");
            }
            else
            {
                return View("NewDishForm");
            }
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChefsNDishes.Models;

namespace ChefsNDishes.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("ShowChefs", "Chef");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Chef/NewChefForm.cshtml
@model ChefsNDishes.Models.Chef

<div class="container">
    <form action="/chefs/new" method="POST" class="form">
        <div class="row">
            <div class="col-1">
                <a href="/chefs">Back</a>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <span asp-validation-for="FirstName" class="text-danger"></span><br />
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                </div>
                
                <div class="form-group">
                    <span asp-validation-for="LastName" class="text-danger"></span><br />
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <span asp-validation-for="Birthday" class="text-danger"></span><br />
                    <label asp-for="Birthday"></label>
                    <input asp-for="Birthday" class="form-control" />
                </div>
                
                <input type="submit" value="Add Chef" class="btn btn-primary mt-5" />
            </div>
        </div>
    </form>
</div>

Views/Chef/ShowChefs.cshtml
@model List<ChefsNDishes.Models.Chef>

<div class="container">
    <div class="row">
        <div class="col">
            <h1>
                Chefs | 
                <a href="/dishes">Dishes</a>
            </h1>
        </div>
        <div class="col-2">
            <a href="/chefs/new">Add a Chef</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2>Check out our roster of Chefs!</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th># of Dishes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var chef in Model)
                    {
                        <tr>
                            <td>
                                @chef.FirstName @chef.LastName
                            </td>
                            <td>
                                @DateTime.MinValue.Add(DateTime.Now.Subtract(@chef.Birthday.AddYears(1))).Year
                            </td>
                            <td>
                                @if (@chef.SignatureDishes != null)
                                {
                                    <p>@chef.SignatureDishes.Count()</p>
                                }
                                else
                                {
                                    <p>0</p>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Dish/NewDishForm.cshtml
@model ChefsNDishes.Models.Dish

<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col">
            <h3>Add a Dish</h3>
        </div>
    </div>
    <form class="form" action="/dishes/new" method="POST">
        <div class="row">
            <div class="col-1">
                <a href="/dishes">Back</a>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <span asp-validation-for="DishName" class="text-danger"></span><br />
                    <label asp-for="DishName"></label>
                    <input asp-for="DishName" class="form-control" />
                </div>

                <div class="form-group">
                    <span asp-validation-for="Calories" class="text-danger"></span><br />
                    <label asp-for="Calories"></label>
                    <input asp-for="Calories" class="form-control" />
                </div>

                <div class="form-group">
                    <span asp-validation-for="Description" class="text-danger"></span><br />
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                </div>
            </div>
            <div class="col-4 position-relative">
                <div class="form-group">
                    <span asp-validation-for="ChefId" class="text-danger"></span><br />
                    <label asp-for="ChefId"></label>
                    <select asp-for="ChefId" class="form-control">
                        @foreach(var chef in @ViewBag.Chefs)
                        {
                            <option value="@chef.ChefId">@chef.FirstName @chef.LastName</option>
                        }
                    </select>
                </div>

                <input type="submit" value="Add Dish" class="btn btn-primary" style="position: absolute; bottom: 10px; right: 10px;" />
            </div>
            <div class="col-3">
                <div class="form-group">
                    <span asp-validation-for="Tastiness" class="text-danger"></span><br />
                    <label asp-for="Tastiness"></label>
                    <select asp-for="Tastiness" class="form-control">
                        <option>5</option>
                        <option>4</option>
                        <option>3</option>
                        <option>2</option>
                        <option>1</option>
                    </select>

                </div>
            </div>
        </div>
    </form>
</div>

Views/Dish/ShowDishes.cshtml
@model List<ChefsNDishes.Models.Dish>

<div class="container">
    <div class="row">
        <div class="col">
            <h1>
                <a href="/chefs">Chefs</a>
                 | 
                Dishes
            </h1>
        </div>
        <div class="col-2">
            <a href="/dishes/new">Add a Dish</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2>Nom nom nom, take a look at our tasty dishes!</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Chef</th>
                        <th>Tastiness</th>
                        <th>Calories</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var dish in Model)
                    {
                        <tr>
                            <td>
                                @dish.DishName
                            </td>
                            <td>
                                @dish.Creator.FirstName @dish.Creator.LastName
                            </td>
                            <td>
                                @dish.Tastiness
                            </td>
                            <td>
                                @dish.Calories
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChefsNDishes</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chefs 'N Dishes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Chef" asp-action="ShowChefs">Chefs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dish" asp-action="ShowDishes">Dishes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ChefsNDishes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>